default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_development1
  host: localhost   # or the hostname or IP of your PostgreSQL server
  port: 5433        # the port where PostgreSQL is running
  username: postgres
  password: "1234" 

test:
  <<: *default
  database: recipe_app_test1
  host: localhost   # or the hostname or IP of your PostgreSQL server
  port: 5433        # the port where PostgreSQL is running
  username: postgres
  password: "1234" 
production:
  <<: *default
  database: recipe_app_production1
  username: recipe_app
  password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>